In 26
InctagramTeam/inctagram-front pull request #141
Opened 2024-10-12 20:05 UTC by stasfilippov

2024-10-14 20:08 UTC, mabar84 requested changes

2024-10-14 20:08 UTC, mabar84 commented on src/pages/my-profile/[id]/settings/general/index.tsx
> +      dateOfBirth: format(dateOfBirth, 'dd-MM-yy'),
нужно заменить на 
dateOfBirth: format(dateOfBirth, 'MM-dd-yyyy'),
 иначе при попытке создать новый профиль в запросе идёт 18-06-99, а в ответе ошибка, что еще не исполнилось 13 лет.
Тестировал так: чистил куки и локалСтораж, через сваггер удалял юзера /api/v1/profile/{userId}. Проходил регистрацию, подтверждал email. После логинился и в ProfileSettings заполнял профиль

2024-10-17 09:54 UTC, mabar84 approved these changes

2024-10-17 10:12 UTC, VladZimin approved these changes

2024-10-17 15:05 UTC, merged